
import:
  - credentials.yml

jobs:
  include:
    - stage: Unit_test
      name: Sanity test
      script:
        - echo "helloworld"
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh | tee merge.log
